[package]
name = "omen-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.8.13"
serde = "1.0"
likemod = "0.2.0"
bisection = "0.1.0"
nix = "0.15.0"
lzma-rs = "0.3.0"
